# Generated by Django 4.1.5 on 2023-01-31 19:27

from django.db import migrations, models
import django.utils.timezone
import first_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('thumnail', models.ImageField(blank=True, null=True, upload_to=first_app.models.user_directory_path)),
                ('excerpt', models.TextField(null=True)),
                ('content', models.TextField(null=True)),
                ('slug', models.SlugField(max_length=250, unique=True, unique_for_date='published')),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'published')], default='draft', max_length=10)),
            ],
        ),
    ]
